# Generated by Django 6.0.7 on 2026-07-09 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year of counseling (e.g., 2023)')),
                ('round_number', models.IntegerField(help_text='Counseling round number')),
                ('category', models.CharField(help_text='e.g., OPEN, OBC-NCL, SC, ST', max_length=50)),
                ('quota', models.CharField(help_text='e.g., AI (All India), HS (Home State)', max_length=50)),
                ('seat_pool', models.CharField(default='Gender-Neutral', help_text='e.g., Gender-Neutral, Female-Only', max_length=50)),
                ('opening_rank', models.IntegerField()),
                ('closing_rank', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='colleges.branch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='colleges.college')),
            ],
            options={
                'ordering': ['-year', 'round_number', 'college', 'branch'],
                'unique_together': {('college', 'branch', 'year', 'round_number', 'category', 'quota', 'seat_pool')},
            },
        ),
    ]
