# Generated by Django 6.0.7 on 2026-07-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='average_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total course fees in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='average_package',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average placement package in INR (LPA)', max_digits=10, null=True),
        ),
    ]
